name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.9.0  # 使用与本地相同的版本
    - name: Check pnpm version
      run: pnpm --version
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Run tests
      run: pnpm test -- --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    - name: Generate coverage badge
      run: |
        COVERAGE=$(node -e "console.log(JSON.parse(require('fs').readFileSync('./coverage/coverage-summary.json')).total.lines.pct)")
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: dcc5fab81ad00c91c8cf90399ac6dba8
        filename: coverage.json
        label: coverage
        message: ${{ env.COVERAGE }}%
        color: green
    - name: Update README
      run: |
        sed -i 's/!\[Coverage\].*/![Coverage](https:\/\/img.shields.io\/endpoint?url=https:\/\/gist.githubusercontent.com\/selfboot\/dcc5fab81ad00c91c8cf90399ac6dba8\/raw\/coverage.json)/' README.md
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update coverage badge" || echo "No changes to commit"
        git push
